### ISSUE TITLE
Segment fault on start : a tiny solution...

### ISSUE THREAD

**Issue by wcdr** [hsharsha/v8inspector#1]
Hi,

I see your post : https://groups.google.com/forum/#!topic/v8-users/kDlkN3Ng67Q - 7 month Old, I known it's old you may solve your problem, or not... When I get your code and compile it crash, so I search for a solution and found one.

You have an error on "sample.js" : x = y;
=> 'y' don't exist if you comment this line you can debug it, see watch, step...

Nice Works,

Bye... 

Dev env : Linux x64 (Ubuntu base), GCC & CLang, v8 : 5.7.492.71.

**Comment by hsharsha** [comment]
Example was illustrated to see if the debugger catches undefined varaible
