### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by StefanWoe** [hsharsha/v8inspector#7]
Thanks for that component. I am looking for the possibility to debug v8 JS in may c++ Windows application.
Does this project support windows?

**Comment by hsharsha** [comment]
Yes, you can build and run on windows. 
[Running cmake on windows](https://cmake.org/runningcmake/)

**Comment by StefanWoe** [comment]
Thanks for this response.
So i understand that a windows build has successfully done and run? 
How difficult will it most likely be to migrate from V8 5.9 (as stated for your project) to V8 7.1 or newer? Will that break the existing code?
