### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by StefanWoe** [hsharsha/v8inspector#8]
How can v8inspector be used?
I embedded v8 into a large application where users can write JS scripts. The scripts are stored in a data base and are executed at specific points some time during execution.
Although we can execute JS files the usual way is a small script passed from a Data base to v8.
Is it possible to use v8inspector to debug such script with a chrome browser or alike?
Regards

Stefan

**Comment by StefanWoe** [comment]
I succeeded to build a windows version of v8inspector and i can start it in the debugger - that was no simple task.. But then nothing more happens. I pass the sample.js as command line argument and i tried several ways to open this file in chrome and to set a break point.  But v8Inspector and chrome do not seem to communicate. 

In your code you create a agent with the 2 arguments
`Agent("localhost", "/tmp/frontend.url");`
What is that meant to say?

How can i debug s simple local js file?
Could you please give some advice on how to start debugging?

**Comment by hsharsha** [comment]
@StefanWoe  Sorry for delay in responding, I was on the move and did not have internet access. Once you build v8inspector, you can start it using v8inspector.exe sample.js. A break point is set by default on the first line of the code and there is a websocket that is opened up for debug session. You need to use that url in chrome to open up debugging session. Same url is also stored in /tmp/frontend.url file.

**Comment by StefanWoe** [comment]
Hello hsharsha. Thanks for your response!
I start inspector.exe sample.js. and then i open chrome and type in the URL
http://localhost/tmp/frontend.url

This ends in ERR_CONNECTION_REFUSED. I set several breakpoints in inspector but none of them is hit.  The line
`    agent->Start() `
in main.cc does not return.  
- Is  /tmp/frontend.url a pyhsical file (there is none in the project)?
- Do i have to use a special port in the url? In TcpView i see that inspector.exe is listening on 2 ports - one for IP4 and one for IP6. When i use these ports in the URL the calls are received in inspector.exe - but HandleGetRequest returns false as no /json is in the url - I think these are the WebSockets for the debugger communication.
- So what is needed to get a reply to the initial localhost/tmp/frontend.url? 
I feel like there is only very little missing...

**Comment by hsharsha** [comment]
@StefanWoe  there is a websocekt url that is printed to console and logged into frontend.url file. Please use that url in the chrome. It should be ws://...

**Comment by StefanWoe** [comment]
Hello hsharsha I see
`Debugger starting on chrome-devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=localhost:50536/00df00cf-00af-40cd-8074-003600d20094
`
When i use the URL
`localhost:50536/00df00cf-00af-40cd-8074-003600d20094`
in chrome, the response is a page consisiting of the text
WebSockets request was expected

**Comment by hsharsha** [comment]
@StefanWoe Its working for you now?

**Comment by StefanWoe** [comment]
No - i found a problem:
inspector tries to create a file /tmp/frontend.url but that directory did not exist (windows).
After creating such a directory the file is created and contains the same string as above.
But still i end up with 
`WebSockets request was expected`

**Comment by hsharsha** [comment]
Please use the complete url `chrome-devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=localhost:50536/00df00cf-00af-40cd-8074-003600d20094`

**Comment by StefanWoe** [comment]
Hello hsharsha.
YES! That seems to work. Thanks a lot!
Ill return with probably more questions.
