### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by StefanWoe** [hsharsha/v8inspector#9]
Hello hsharsha - thanks again for your help to get things work.
Your project is a great help!

I am trying to understand your implementation. A few questions:
- The file "/tmp/frontend.url" seems to be unneeded. I remove the code to create it - and deleted the file. the debugger still works. Why do you create this file?

- Find a lot of code that is never called during a simple debugging session.
InspectorSocketServer::HandleGetRequest never is called with a "/json" part so the containing functions are never called. Debugging works if HandleGetRequest just always returns false.
When will the other branches in this function be called (list, protocol etc..)?

- Also from Agent::Start(.... const char* path) the last argument path can be omitted while still keeping debugging possible - whats the purpose of this file path?

- Can you point me to a deeper documentation of the debugging protocol than in https://v8.dev/docs/inspector?

**Comment by hsharsha** [comment]
@StefanWoe forntend.url was created for applications that cannot read from stdout. It is just a buffer which can be consumed by other applications as needed. It can be removed.

Most of the code is copied from node code base for a standard websocket server, We probably use only a small subset of the same.

Again path is for the file buffer and can be removed.

v8 documentation (if we can call that as documentation :)  is the best bet now. 
I plan to separate out websocket server, libuv dependency and write more descriptive documentation around v8 inspector, but not sure when. Also this code has dependency on v8 5.9 version and I am not sure if this protocol is compatible with latest v8.

**Comment by StefanWoe** [comment]
Hi hsharsha. Thanks for your answer.
Just a note: The code works fine with v8 Version 7.1.302.4 on Windows.
